//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class AOI_Component
    {
        public int Component_Id { get; set; }
        public int Board_Id { get; set; }
        public string Component_Name { get; set; }
        public int Defect_Type_Id { get; set; }
        public int Repair_State_Result_Id { get; set; }
        public string Algorithm { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> Feeder_Id { get; set; }
        public string RemarkDefectType { get; set; }
    
        public virtual AOI_Board AOI_Board { get; set; }
        public virtual Defect_Type Defect_Type { get; set; }
        public virtual Feeder Feeder { get; set; }
        public virtual Result Result { get; set; }
    }
    
}
