//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class AOI_Board
    {
        public AOI_Board()
        {
            this.AOI_Component = new HashSet<AOI_Component>();
        }
    
        public int Board_Id { get; set; }
        public int Panel_Id { get; set; }
        public string Board_Barcode { get; set; }
        public int Result_Id { get; set; }
        public Nullable<int> Total_Comps_Num { get; set; }
        public Nullable<int> Total_Pins_Num { get; set; }
        public Nullable<int> Indict_Comps_Num { get; set; }
        public Nullable<int> Indict_Pins_Num { get; set; }
        public Nullable<int> Defect_Num { get; set; }
        public Nullable<int> Active_Defect_Num { get; set; }
        public Nullable<int> Active_Pins_Num { get; set; }
        public Nullable<int> Active_Comps_Num { get; set; }
        public Nullable<int> FalseCall_Defect_Num { get; set; }
        public Nullable<int> FalseCall_Pins_Num { get; set; }
        public Nullable<int> FalseCall_Comps_Num { get; set; }
    
        public virtual ICollection<AOI_Component> AOI_Component { get; set; }
        public virtual AOI_Panel AOI_Panel { get; set; }
        public virtual Result Result { get; set; }
    }
    
}
