//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class Building
    {
        public Building()
        {
            this.Segments = new HashSet<Segment>();
        }
    
        public int Building_Id { get; set; }
        public string Building_Name { get; set; }
        public bool Is_Active { get; set; }
        public int Creator_Id { get; set; }
        public System.DateTime Creation_Time { get; set; }
        public System.DateTime Effect_Time { get; set; }
    
        public virtual ICollection<Segment> Segments { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
    
}
