//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class Feeder
    {
        public Feeder()
        {
            this.AOI_Component = new HashSet<AOI_Component>();
        }
    
        public int Feeder_Id { get; set; }
        public int Station_Id { get; set; }
    
        public virtual ICollection<AOI_Component> AOI_Component { get; set; }
        public virtual Station Station { get; set; }
    }
    
}
