//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class Machine_Model
    {
        public Machine_Model()
        {
            this.Machines = new HashSet<Machine>();
        }
    
        public int Machine_Model_Id { get; set; }
        public int Machine_Brand_Id { get; set; }
        public int Machine_Type_Id { get; set; }
        public string Machine_Model_Name { get; set; }
        public string Machine_Picture_Url { get; set; }
        public int Creator_Id { get; set; }
        public System.DateTime Creation_Time { get; set; }
    
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual Machine_Brand Machine_Brand { get; set; }
        public virtual Machine_Type Machine_Type { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
    
}
