//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class Machine
    {
        public Machine()
        {
            this.Stations = new HashSet<Station>();
        }
    
        public int Machine_Id { get; set; }
        public string Machine_Asset_Num { get; set; }
        public string Machine_Name { get; set; }
        public int Machine_Status_Id { get; set; }
        public int Machine_Model_Id { get; set; }
        public int Building_Id { get; set; }
        public int Creator_Id { get; set; }
        public System.DateTime Creation_Time { get; set; }
    
        public virtual Machine_Model Machine_Model { get; set; }
        public virtual ICollection<Station> Stations { get; set; }
        public virtual Machine_Status Machine_Status { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
    
}
