//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class Machine_Status
    {
        public Machine_Status()
        {
            this.Machines = new HashSet<Machine>();
        }
    
        public int Machine_Status_Id { get; set; }
        public string Machine_Status1 { get; set; }
        public int Creator_Id { get; set; }
        public System.DateTime Creation_Time { get; set; }
    
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
    
}
