//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class Machine_Type
    {
        public Machine_Type()
        {
            this.Defect_Type = new HashSet<Defect_Type>();
            this.Machine_Model = new HashSet<Machine_Model>();
            this.Results = new HashSet<Result>();
        }
    
        public int Machine_Type_Id { get; set; }
        public string Machine_Type_Name { get; set; }
        public int Creator_Id { get; set; }
        public System.DateTime Creation_Time { get; set; }
    
        public virtual ICollection<Defect_Type> Defect_Type { get; set; }
        public virtual ICollection<Machine_Model> Machine_Model { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
    
}
