//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class Segment
    {
        public Segment()
        {
            this.BusinessUnits = new HashSet<BusinessUnit>();
            this.Lines = new HashSet<Line>();
            this.Projects = new HashSet<Project>();
        }
    
        public int Segment_Id { get; set; }
        public string Segment_Name { get; set; }
        public string Segment_Code { get; set; }
        public bool Is_Active { get; set; }
        public int Building_Id { get; set; }
        public int Creator_Id { get; set; }
        public System.DateTime Creation_Time { get; set; }
        public System.DateTime Effect_Time { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual ICollection<BusinessUnit> BusinessUnits { get; set; }
        public virtual ICollection<Line> Lines { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
    
}
