//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class SPI_Board
    {
        public SPI_Board()
        {
            this.SPI_Pad = new HashSet<SPI_Pad>();
        }
    
        public int Board_Id { get; set; }
        public int Panel_Id { get; set; }
        public string Board_Name { get; set; }
        public string Board_Barcode { get; set; }
        public Nullable<int> Result_Id { get; set; }
        public int TotalPads_Num { get; set; }
        public int ErrorPads_Num { get; set; }
    
        public virtual Result Result { get; set; }
        public virtual ICollection<SPI_Pad> SPI_Pad { get; set; }
        public virtual SPI_Panel SPI_Panel { get; set; }
    }
    
}
