//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class SPI_Pad
    {
        public int Pad_Id { get; set; }
        public int Board_Id { get; set; }
        public string Component_Name { get; set; }
        public int Defect_Type_Id { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Real_Area { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> Real_Volume { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> Offset_X { get; set; }
        public Nullable<double> Offset_Y { get; set; }
        public Nullable<double> Position_X { get; set; }
        public Nullable<double> Position_Y { get; set; }
        public Nullable<double> Pad_X { get; set; }
        public Nullable<double> Pad_Y { get; set; }
    
        public virtual Defect_Type Defect_Type { get; set; }
        public virtual SPI_Board SPI_Board { get; set; }
    }
    
}
