//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISPC.EntityFramework
{
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Buildings = new HashSet<Building>();
            this.BusinessUnits = new HashSet<BusinessUnit>();
            this.Lines = new HashSet<Line>();
            this.Machines = new HashSet<Machine>();
            this.Machine_Brand = new HashSet<Machine_Brand>();
            this.Machine_Model = new HashSet<Machine_Model>();
            this.Machine_Status = new HashSet<Machine_Status>();
            this.Machine_Type = new HashSet<Machine_Type>();
            this.Models = new HashSet<Model>();
            this.Projects = new HashSet<Project>();
            this.Results = new HashSet<Result>();
            this.Segments = new HashSet<Segment>();
            this.Stations = new HashSet<Station>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual ICollection<BusinessUnit> BusinessUnits { get; set; }
        public virtual ICollection<Line> Lines { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual ICollection<Machine_Brand> Machine_Brand { get; set; }
        public virtual ICollection<Machine_Model> Machine_Model { get; set; }
        public virtual ICollection<Machine_Status> Machine_Status { get; set; }
        public virtual ICollection<Machine_Type> Machine_Type { get; set; }
        public virtual ICollection<Model> Models { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<Segment> Segments { get; set; }
        public virtual ICollection<Station> Stations { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
    
}
